default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  host: <%= ENV["DB_HOST"] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  <<: *default
  database: todo_list_ibc_development

test:
  adapter: mysql2
  <<: *default
  database: todo_list_ibc_test

production:
  adapter: postgresql
  <<: *default
  database: todo_list_ibc_production
  username: todo_list_ibc
  password: <%= ENV['TUDO_LIST_IBC_DATABASE_PASSWORD'] %>

# Create file /config/application.yml with the data:
# DB_USER: "user_database"
# DB_PASS: "password_databases"
# DB_HOST: "ip_vicidial_database"